final = True

bioPath = '/home/kpopprofilebot/botsite/botpage/idolbio.csv' if final else "botpage/idolbio.csv"
groupsPath = '/home/kpopprofilebot/botsite/botpage/idolgroups.csv' if final else "botpage/idolgroups.csv"
factsPath = '/home/kpopprofilebot/botsite/botpage/idolfacts.csv' if final else "botpage/idolfacts.csv"
foodPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/foods.csv' if final else "botpage/factGenerators/foods.csv"
mottoPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/mottos.csv' if final else "botpage/factGenerators/mottos.csv"
moviesPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/movies.csv' if final else "botpage/factGenerators/movies.csv"
moviesDisneyPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/moviesDisney.csv' if final else "botpage/factGenerators/moviesDisney.csv"
representativePath = '/home/kpopprofilebot/botsite/botpage/factGenerators/representative.csv' if final else "botpage/factGenerators/representative.csv"
charmPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/charmPoints.csv' if final else "botpage/factGenerators/charmPoints.csv"
habitPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/habits.csv' if final else "botpage/factGenerators/habits.csv"
roleModelPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/rolemodels.csv' if final else "botpage/factGenerators/rolemodels.csv"
englishNamePath = '/home/kpopprofilebot/botsite/botpage/factGenerators/englishNames.csv' if final else "botpage/factGenerators/englishNames.csv"
fearsPath = '/home/kpopprofilebot/botsite/botpage/factGenerators/fears.csv' if final else "botpage/factGenerators/fears.csv"